config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles do
    resources :comments
  end

  resources :users 

  # email subscribe path to UsersController 
  patch "users/:id/email_subscribe", to: "users#email_subscribe", as: :email_subscribe  

  # there should not be a create resource on the shallow route
  resources :comments, except: [:new, :create] do
    resources :comments
  end

  get 'home', to: 'home#index', as: :home
  get 'home', to: 'home#index', as: :user_root

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_closure_tree
  # Constants
  
  # Active Record Relationships
  belongs_to :commentable, polymorphic: :true
  belongs_to :commenter, class_name: 'User', foreign_key: 'commenter_user_id' 

  # Validations
  validates :body, presence: true
  validates :commentable, presence: true


  # Scopes 

  # Class Methods
  
  # Public Instance Methods

  # Protected Instance Methods

  # Private Instance Methods  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource 
  before_action :find_commentable, only: [:create]
  before_action :find_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all.order(created_at: :desc)
  end
  
  def show
  end

  def edit
    @commentable = @comment.commentable
  end

  def create    
    @comment = @commentable.comments.new(comment_params)
    @comment.commenter = current_user
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to @commentable
    else
      flash[:notice] = 'Comment not created due to error.'
    end      
  end

  def update
    if @comment.update(comment_params)    
      flash[:notice] = 'Comment was successfully updated.'
      redirect_to @comment
    else
      flash[:alert] = 'Comment was not updated due to errors.'
      render :edit
    end
  end

  def destroy
    @commentable = @comment.commentable
    @comment.destroy
    flash[:notice] = 'Comment was successfully destroyed.'
    redirect_to @commentable
  end

  private
  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body, :parent_id)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <% 
    max_nesting = 6
    if controller.controller_name == 'comments'
      div_grid_columns = 12
      div_grid_offset = 0      
    elsif comment.depth > max_nesting
      div_grid_columns = 12 - max_nesting
      div_grid_offset = max_nesting
    else
      div_grid_columns = 12 - comment.depth
      div_grid_offset = comment.depth 
    end
  %>
  <%= content_tag('div', class: "col-xs-#{div_grid_columns} offset-xs-#{div_grid_offset}") do %>
    <div class="card stateless-comment-partial-card %>">
      <div class="card-header">
        <% if controller.controller_name == 'comments' && controller.action_name == 'index' %>
          <h2>Comment by <%= comment.commenter.username %> on <%= link_to comment.commentable.title, comment.commentable %></h2> 
        <% end %>
        <!-- TODO: Update after improving user name display -->
        <h5><%= image_tag comment.commenter.avatar.url(:thumb), alt: "#{comment.commenter.username}'s avatar", class: 'float-left' %> <%= comment.commenter.username %></h5>
        <h6 class="card-subtitle text-muted"><%= l(comment.created_at, format: :short) %></h6>
      </div>  
      <div class="card-block">
        <p class="card-text"><%= comment.body %></p>    
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-4">
            <%= link_to "View Thread", comment_path(comment) %>
          </div>
          <!-- TODO: Add user method to improve name options -->
          <div class="col-md-4 text-md-center">
            <% if can? :destroy, comment %>        
              <%= link_to("Destroy #{comment.parent_id.nil? ? 'Comment' : 'Reply'}", [comment.commentable, comment], method: :delete, data: {confirm: 'Are you sure'})%>
            <% end %>
          </div>
          <div class="col-md-4 text-md-right">
            <%= link_to "#{comment.children.length} #{'reply'.pluralize(comment.children.length)}", comment_path(comment, anchor: 'statelessCommentShowReplyHeaderCard') %>
          </div>
        </div>  
      </div>
    </div>
    <% end %>
</div>
<% if comment.children.any? && controller.controller_name != 'comments' %>
  <%= render comment.children %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([commentable, comment]) do |f| %>  
    <%= f.hidden_field :parent_id, value: parent_id %>
    <div class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: 'form-control', rows: 3 %>
    </div>  
    <%= f.button type: 'submit', class: 'btn btn-primary' do %>
      Submit Comment
    <% end %>
<% end %>

app/views/comments/edit.html.erb
<%= title "Edit Comment on #{@comment.commentable.title}" %>
<%= meta_description "Edit Comment by #{@comment.commenter.username} on #{@comment.commentable.title}." %>
<%= meta_keywords (['comments', 'edit', @comment.commenter.username, @comment.commentable_type] << @comment.commentable.keywords).reject{|el| el.blank?}.uniq.join(',') %>

<div class="row">    
  <div class="content-card-container"> 
    <div class="row">
      <div class="col-xs-12">
        <div class="card card-block">
          <h1 id="commentsEditTitle" class="card-title display-4"><%= image_tag @comment.commenter.avatar.url(:small), alt: "#{@comment.commenter.username}'s avatar", class: 'float-left' %> <%= "Edit Comment on #{@comment.commentable.title}" %></h1>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1 edit-container">
        <div class="card stateless-comment-partial-card">
          <div class="card-block">
            <div class="card-text">
              <%= render 'form', commentable: @commentable, comment: @comment, commentable_type: @commentable.class.to_s, commentable_id: @commentable.id, parent_id: @comment.parent_id %>
            </div>          
          </div>            
        </div>        
      </div>
    </div>
    <div class="row bottom-buttons">
      <div class="col-xs-12 text-xs-center">
        <%= link_to comment_path(@comment), class: "btn btn-primary" do %>
          <%= fa_icon 'circle-left', text: 'Back to Comment' %>
        <% end %>
        <%= link_to @comment.commentable, class: "btn btn-primary" do %>
          <%= fa_icon 'circle-left', text: "Back to #{@comment.commentable_type}" %>    
        <% end %>
        <%= link_to comment_path(@comment), method: :delete, class: "btn btn-secondary", data: {confirm: 'Are you sure?'} do %>
          <%= fa_icon 'remove', text: 'Destroy' %>
        <% end %>  
        <%= link_to 'Comment Feed', comments_path, class: "btn btn-secondary" %>
      </div>  
    </div>
  </div>    
</div>

app/views/comments/index.html.erb
<div class="row">    
  <div class="content-card-container"> 
    <div class="row">
      <div class="col-xs-12">
        <div class="card card-block">
          <h1 id="commentsIndexTitle" class="card-title display-4"><%= t "meta.comments_index.title" %></h1>
          <h6 class="card-subtitle text-muted"><%= t "meta.comments_index.description" %></h6>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1 index-container">
        <%= render @comments %>        
      </div>
    </div>
    <div class="row bottom-buttons">
      <div class="col-xs-12 text-xs-center">
        <%= link_to articles_path, class: 'btn btn-primary' do %>
          Articles
        <% end %>            
        <%= link_to root_path, class: 'btn btn-primary' do %>
          <%= fa_icon 'home', text: 'Main site page' %>
        <% end %>
      </div>
    </div>        
  </div>
</div>

app/views/comments/show.html.erb
<%= title "Comment by #{@comment.commenter.username} on #{@comment.commentable.title}" %>
<%= meta_description "Comment by #{@comment.commenter.username} on #{@comment.commentable.title}. #{@comment.commentable.description}"[0...200] %>
<%= meta_keywords (['comments', @comment.commenter.username, @comment.commentable_type] << @comment.commentable.keywords).reject{|el| el.blank?}.uniq.join(',') %>

<div class="row">    
  <div class="content-card-container"> 
    <div class="row">
      <div class="col-xs-12">
        <div class="card card-block">
          <h1 id="CommentsShowTitle" class="card-title display-4"><%= image_tag @comment.commenter.avatar.url(:small), alt: "#{@comment.commenter.username}'s avatar", class: 'float-left' %> Comment by <%= @comment.commenter.username %> on <%= link_to @comment.commentable.title, @comment.commentable %></h1>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1 individual-container">
        <div id="statelessCommentShowCard" class="card">
          <div class="card-header">
            <div class="row">
              <div class="col-md-4 text-md-left">
                <!-- TODO: Add user method to improve name options -->
                <h6 class="text-muted"><strong>By:</strong> <%= @comment.commenter.username %></h6>
              </div>
              <div class="col-md-4 text-md-right">  
                <h6 class="text-muted text-xs-right"><strong>Posted:</strong> <%= l(@comment.created_at, format: :short)  %></h6>
              </div>
            </div>
          </div>
          <div class="card-block">
            <div class="row">
              <div class="col-md-10 offset-md-1">              
                <p class="card-text"><%= @comment.body %></p>
              </div>
            </div>              
          </div>
        </div>        
        <div id="statelessCommentShowReplyHeaderCard" class="card">
          <div class="card-block">
            <h3  class="card-title"><%= "#{@comment.children.length} #{'reply'.pluralize(@comment.children.length)}" %></h3>
          </div>
        </div>
        <%= render @comment.children %>
        <div class = "row">
          <div class="col-xs-12">
            <div id="statelessCommentShowNewReply" class="card card-outline-secondary col-xs-12">
              <div class="card-block">
                <h3 class="card-title">Add a Reply:</h3>
                <%= render 'comments/form', commentable: @comment.commentable, comment: Comment.new, commentable_type: @comment.commentable_type, commentable_id: @comment.commentable_id, parent_id: @comment.id %>
              </div>
            </div>
          </div>  
        </div>
        <div class="row bottom-buttons">
          <div class="col-xs-12 text-xs-center">
            <%= link_to edit_comment_path(@comment), class: "btn btn-primary" do %>
              <%= fa_icon 'edit', text: 'Edit' %>
            <% end %>
            <%= link_to @comment.commentable, class: "btn btn-primary" do %>
              <%= fa_icon 'circle-left', text: "Back to #{@comment.commentable_type}" %>    
            <% end %>
            <%= link_to comment_path(@comment), method: :delete, class: "btn btn-secondary", data: {confirm: 'Are you sure?'} do %>
              <%= fa_icon 'remove', text: 'Destroy' %>
            <% end %>  
            <%= link_to 'Comment Feed', comments_path, class: "btn btn-secondary" %>
          </div>  
        </div>    
      </div>  
    </div>
  </div>
</div>