config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles do
    resources :comments
  end

  resources :users 

  # email subscribe path to UsersController 
  patch "users/:id/email_subscribe", to: "users#email_subscribe", as: :email_subscribe  

  # there should not be a create resource on the shallow route
  resources :comments, except: [:new, :create] do
    resources :comments
  end

  get 'home', to: 'home#index', as: :home
  get 'home', to: 'home#index', as: :user_root

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  # Devise
  # Include default devise modules. Others available are:
  # :omniauthable add later
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable


  # Hooks

  # Constants
 
  # Active Record Relationships
  has_many :comments, class_name: 'Comment', foreign_key: 'commenter_user_id', dependent: :nullify
  has_many :articles, class_name: 'Article', foreign_key: 'author_user_id', dependent: :nullify
  has_attached_file :avatar, styles: { medium: "400x400>", small: "100x100>", thumb: "32x32>" }, default_url: "/images/:style/missing.png"
  


  # Scopes 

  # Class Methods
  def self.roles
    ['Admin', 'Moderator', 'Author', 'Subscriber', 'Public']
  end

  def self.subscription_classes
    ['Master', 'Active', 'Expired', 'Email', 'Public']
  end

  def self.user_classes
    ['Staff', 'Legend', 'Elite User', 'Extreme User', 'Power User', 'User', 'Guest']
  end

  # Validations
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, allow_nil: true, allow_blank: true
  validates_with AttachmentPresenceValidator, attributes: :avatar, allow_nil: true, allow_blank: true
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 500.kilobytes 
  validates :role, inclusion: {in: User.roles} 
  validates :role, inclusion: {in: User.roles} 
  validates :subscription_class, inclusion: {in: User.subscription_classes}
  validates :user_class, inclusion: {in: User.user_classes} 


  # Public Instance Methods
  def is_admin?
    self.role == 'Admin' ? true : false
  end
  # Protected Instance Methods

  # Private Instance Methods


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource 
  before_action :find_user, only: [:show, :edit, :update, :destroy, :email_subscribe]

  def show

  end

  def edit

  end

  def update
    if @user.update(user_params)    
      flash[:notice] = 'User profile was successfully updated.'
      redirect_to @user
    else
      flash[:alert] = 'User profile was not updated due to errors.'
      render :edit
    end    
  end

  # other routes
  def email_subscribe
    @user.update(email_subscriber: true)
    # TODO: send welcome email here
    flash[:notice] = "Thank you for joining the Stateless Code email distibution!"
    redirect_to @user
  end


  private
  def user_params
    params.require(:user).permit(:username, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#Edit</h1>

app/views/users/show.html.erb
<%= title "Profile for #{@user.username}" %>
<%= meta_description "The Stateless Code profile for #{@user.username}" %>
<%= meta_keywords "stateless, code, users, #{@user.username}" %>

<div class="row">    
  <div class="content-card-container"> 
    <div class="row">
      <div class="col-xs-12">
        <div class="card card-block">
          <h1 id="usersShowTitle" class="card-title display-4"><%= @user.username %>'s Profile</h1>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1 individual-container">
        <div id="statelessUserShowCard" class="card">
          <div class="card-header">
            <div class="row">
              <div class="col-md-4 text-md-left">
                <!-- TODO: Add user method to improve name options -->
                <h6 class="text-muted"><strong>Left:</strong></h6>
              </div>
              <div class="col-md-4 text-md-center">
                <!-- TODO: Make topics linkable -->
                <h6 class="text-muted text-xs-right text-md-center"><strong>Middle:</strong></h6>
              </div>  
              <div class="col-md-4 text-md-right">  
                <h6 class="text-muted text-xs-right"><strong>Right:</strong></h6>
              </div>
            </div>
          </div>
          <div class="card-block">            
            <div class="row">
              <div class="col-md-10 offset-md-1">
                <dl class="row">
                  <dt class="col-sm-5 col-xl-4">Username:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= @user.username %></dd>

                  <dt class="col-sm-5 col-xl-4">Preferred Display Name:</dt>
                  <dd class="col-sm-7 col-xl-8">To be implemented</dd>

                  <dt class="col-sm-5 col-xl-4">Email Address:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= @user.email %></dd>                


                  <dt class="col-sm-5 col-xl-4">Email Subscriber:</dt>                  
                  <dd class="col-sm-7 col-xl-8">
                    <% if @user.email_subscriber %> 
                      Subscribed
                    <% else %>
                      Not Subcribed <%= link_to('Sign Up', email_subscribe_path(@user), method: :patch, class: "btn btn-sm btn-success") %>
                    <% end %>
                  </dd>

                  <dt class="col-sm-5 col-xl-4">Role:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= @user.role %></dd>

                  <dt class="col-sm-5 col-xl-4">Subscription Level:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= @user.subscription_class %></dd>

                  <dt class="col-sm-5 col-xl-4">Class:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= @user.user_class %></dd>
                  
                  <dt class="col-sm-5 col-xl-4">Joined at:</dt>
                  <dd class="col-sm-7 col-xl-8"><%= l(@user.created_at)%></dd>
                </dl>
              </div>
            </div>
            <div class='row'>
              <div class="col-md-10 offset-md-1">
                <h4>Avatar:</h4>
                <%= image_tag(@user.avatar, {alt: "#{@user.username}'s Avatar", class: 'img-fluid'}) %>

                <%= form_for @user, url: user_path(@user) do |f| %>
                  <%= f.file_field :avatar %>
                  <%= f.submit('Upload')%>
                <% end %>
              </div>
            </div>              
          </div>
          <div class="card-footer text-muted clearfix">
            <div class="row">
              <!-- TODO: Make keywords linkable -->
              <div class="col-md-12 text-md-center">Footer stuff</div>
            </div>
          </div>  
        </div>        
        <div class="row bottom-buttons">
          <div class="col-xs-12 text-xs-center">
            <%= link_to edit_user_path(@user), class: "btn btn-primary" do %>
              <%= fa_icon 'edit', text: 'Edit Profile' %>
            <% end %>
            <!-- link to some Devise actions here -->

            <%= link_to 'Back to Site Home', root_path, class: "btn btn-secondary" %>
          </div>  
        </div>    
      </div>  
    </div>
  </div>
</div>